[package]
name = "xsend-desktop"
version = "0.1.0"
description = "xSend desktop (Tauri 2)"
authors = ["xsend"]
edition = "2024"

[build-dependencies]
tauri-build = { version = "2" }

[dependencies]
anyhow = "1.0.79"
tauri = { version = "2" }
xsend = { path = "../.." }

